#
# Automata Studio
# Copyright (c) 2025, Gerald Corzo
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#

"""
This module provides common utility functions for the environments package,
including saving simulation data and generating analysis reports.
"""

import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import os
from datetime import datetime
import matplotlib.animation as animation

# --- Data Saving ---

def save_as_netcdf(ca_images: np.ndarray, variable_name: str, output_file: str):
    """
    Saves a 3D numpy array of CA states to a NetCDF file with a named variable.

    Args:
        ca_images (np.ndarray): A numpy array with dimensions (time, y, x).
        variable_name (str): The name for the data variable (e.g., 'ca_state').
        output_file (str): The path to the output .nc file.
    """
    steps, height, width = ca_images.shape
    
    # Create a DataArray with coordinates
    data_array = xr.DataArray(
        ca_images,
        dims=["time", "y", "x"],
        coords={"time": np.arange(steps), "y": np.arange(height), "x": np.arange(width)},
        name=variable_name
    )
    
    # Create a Dataset to hold the DataArray
    dataset = xr.Dataset({variable_name: data_array})
    
    # Add metadata
    dataset.attrs['description'] = 'Cellular Automata simulation data generated by Automata Studio.'
    dataset.attrs['created_by'] = 'Gerald Corzo'
    dataset.attrs['creation_date'] = datetime.utcnow().isoformat()
    
    dataset.to_netcdf(output_file)
    print(f"✅ Successfully saved environment to {output_file}")

# --- Reporting and Analysis ---

def generate_report(netcdf_file: str, report_dir: str = "report"):
    """
    Analyzes a simulation .nc file and generates a markdown report with plots.

    Args:
        netcdf_file (str): Path to the input .nc file.
        report_dir (str): Directory to save the report and plot images.
    """
    if not os.path.exists(report_dir):
        os.makedirs(report_dir)
        
    print(f"📊 Generating analysis report for {netcdf_file}...")

    # Load the dataset
    ds = xr.open_dataset(netcdf_file)
    variable_name = list(ds.data_vars)[0]
    data = ds[variable_name]

    # --- Calculations ---
    time_series_mean = data.mean(dim=['x', 'y']).values
    time_series_max = data.max(dim=['x', 'y']).values
    time_series_min = data.min(dim=['x', 'y']).values
    
    # Find the frame with the maximum sum
    frame_sums = data.sum(dim=['x', 'y'])
    max_sum_frame_index = frame_sums.argmax().item()
    max_sum_frame = data.isel(time=max_sum_frame_index).values
    
    # --- Plotting ---
    
    # 1. Time Series Plot
    plt.figure(figsize=(12, 6))
    plt.plot(time_series_mean, label='Mean Value', color='blue')
    plt.plot(time_series_max, label='Max Value', linestyle='--', color='red')
    plt.plot(time_series_min, label='Min Value', linestyle='--', color='green')
    plt.title('Statistical Trends Over Time')
    plt.xlabel('Time Step')
    plt.ylabel('Cell Value')
    plt.legend()
    plt.grid(True, alpha=0.5)
    plot_path_ts = os.path.join(report_dir, 'timeseries_stats.png')
    plt.savefig(plot_path_ts)
    plt.close()
    
    # 2. Histograms
    plt.figure(figsize=(12, 6))
    plt.subplot(1, 2, 1)
    plt.hist(data.values.flatten(), bins=50, color='purple')
    plt.title('Overall Value Distribution (All Steps)')
    plt.xlabel('Cell Value')
    plt.ylabel('Frequency')
    
    plt.subplot(1, 2, 2)
    plt.hist(max_sum_frame.flatten(), bins=50, color='orange')
    plt.title(f'Value Distribution (at Peak, Time={max_sum_frame_index})')
    plt.xlabel('Cell Value')
    plot_path_hist = os.path.join(report_dir, 'histograms.png')
    plt.savefig(plot_path_hist)
    plt.close()

    # 3. Initial and Final State
    plt.figure(figsize=(12, 6))
    plt.subplot(1, 2, 1)
    plt.imshow(data.isel(time=0), cmap='binary')
    plt.title('Initial State (Time = 0)')
    plt.axis('off')
    
    plt.subplot(1, 2, 2)
    plt.imshow(data.isel(time=-1), cmap='binary')
    plt.title(f'Final State (Time = {len(data.time)-1})')
    plt.axis('off')
    plot_path_states = os.path.join(report_dir, 'state_snapshots.png')
    plt.savefig(plot_path_states)
    plt.close()

    # --- Markdown Generation ---
    report_md_path = os.path.join(report_dir, 'report.md')
    with open(report_md_path, 'w') as f:
        f.write(f"# Automata Studio: Simulation Report\n\n")
        f.write(f"**Source File:** `{netcdf_file}`\n")
        f.write(f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        f.write("## Summary Statistics\n")
        f.write(f"- **Dimensions:** {data.dims}\n")
        f.write(f"- **Shape:** {data.shape}\n")
        f.write(f"- **Overall Mean Value:** {data.mean().item():.4f}\n")
        f.write(f"- **Overall Std Dev:** {data.std().item():.4f}\n\n")

        f.write("## State Snapshots\n\n")
        f.write("A look at the initial and final configurations of the grid.\n\n")
        f.write("![Initial and Final States](state_snapshots.png)\n\n")

        f.write("## Time Series Analysis\n\n")
        f.write("This chart shows the evolution of the grid's mean, maximum, and minimum cell values over time.\n\n")
        f.write("![Time Series Stats](timeseries_stats.png)\n\n")

        f.write("## Distribution Analysis\n\n")
        f.write("These histograms show the frequency of cell values, both for the entire simulation and for the single time step with the highest total cell value sum.\n\n")
        f.write("![Histograms](histograms.png)\n\n")

    print(f"✅ Report successfully generated in '{report_dir}' directory.")


def visualize_simulation(netcdf_file: str, save_gif: bool = False, interval: int = 50):
    """
    Creates an interactive animation from a simulation .nc file with a dynamic title.

    Args:
        netcdf_file (str): Path to the input .nc file.
        save_gif (bool): If True, saves the animation as a GIF.
        interval (int): Delay between frames in milliseconds.
    """
    print(f"🎬 Creating animation for {netcdf_file}...")

    ds = xr.open_dataset(netcdf_file)
    variable_name = list(ds.data_vars)[0]
    data = ds[variable_name]
    total_steps = len(data.time) - 1

    fig, ax = plt.subplots(figsize=(8, 8))
    im = ax.imshow(data.isel(time=0), cmap='binary')
    ax.set_axis_off()
    
    # Add a main title for the simulation type
    fig.suptitle(f"Simulation: {netcdf_file}", fontsize=16)

    def update(frame):
        # Update the image data for the current frame
        im.set_array(data.isel(time=frame))
        
        # Calculate the current population (sum of active cells)
        population = np.sum(data.isel(time=frame).values)
        
        # Update the title for each frame with step and population info
        ax.set_title(f"Time Step: {frame}/{total_steps} | Population: {population}", fontsize=12)
        return im,

    # Set blit=False to ensure the title text is updated on every frame
    ani = animation.FuncAnimation(
        fig,
        update,
        frames=len(data.time),
        interval=interval,
        blit=False  # IMPORTANT: This is the fix for the title update
    )

    if save_gif:
        gif_path = netcdf_file.replace('.nc', '.gif')
        print(f"💾 Saving animation to {gif_path}...")
        ani.save(gif_path, writer='pillow', fps=1000/interval)
        print("✅ Save complete.")

    plt.tight_layout(rect=[0, 0, 1, 0.96]) # Adjust layout to prevent title overlap
    plt.show()
# --- End of common.py ---